### ISSUE TITLE
Password & token leak

### ISSUE THREAD

**Issue by vynmera** [zermelo-discord/discordbot#2]
You're leaking a bot token and other passwords/connection info here!! https://github.com/zermelo-discord/discordbot/blob/master/src/main/java/com/lucasvanbeek/zermelodiscord/Main.java

**Comment by vynmera** [comment]
Looks like you fixed it :+1: Make sure to change those passwords and tokens!

**Comment by MrWouterNL** [comment]
Did that, for sure. Had some issues with Github (quite a big noob to be fair) but changed them when I saw your issue, thanks for reporting it!
